# Generated by Django 5.1.6 on 2025-03-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_service', '0007_alter_event_timeline_alter_event_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project_id', 'user_id'), name='user_once_per_project'),
        ),
    ]
