# Generated by Django 5.1.6 on 2025-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_service', '0009_projectmember_created_at_alter_event_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='Event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='timeline',
            constraint=models.CheckConstraint(condition=models.Q(('timeline_end__gt', models.F('timeline_start'))), name='Timeline_end_after_start'),
        ),
    ]
