# Generated by Django 5.1.6 on 2025-03-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_service', '0011_remove_event_event_end_after_start_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Event_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='timeline',
            name='Timeline_end_after_start',
        ),
    ]
