services:
  user-service:
    build: ./user_service
    ports:
      - "$USR_PORT:$USR_PORT"
    env_file:
      - .env

  project-service:
    build: ./project_service
    ports:
      - "$PRJ_PORT:$PRJ_PORT"
    env_file:
      - .env

  manager-service:
    build: ./manager_service
    ports:
      - "$MAN_PORT:$MAN_PORT"
    env_file:
      - .env

  hr-service:
    build: ./hr_service
    ports:
      - "$HR_PORT:$HR_PORT"
    env_file:
      - .env

  doc-service:
    build: ./doc_service
    ports:
      - "$DOC_PORT:$DOC_PORT"
    env_file:
      - .env
# linux: sudo docker compose build {name}-service
# sudo docker compose up {name}-service