services:
  project-service:
    build: ./project_service
    ports:
      - "$PRJ_PORT:$PRJ_PORT"
    env_file:
      - .env
# linux: sudo docker compose build {name}-service
# sudo docker compose up {name}-service
